### PR TITLE
Send entity information on join to node joining. Closes #91

### LINKED ISSUE #91: New node joining does not receive entities from other nodes
**New node joining does not receive entities from other nodes**

A node joining a cluster does only dispatch a `{:join, entities}` to the other nodes of the cluster
but does not receive any information about the entities which the other nodes hold. So if a node joins after
another node the first node will not receive any entity information.

Edit: I noticed the orchestrator runs the discovery periodically, which will fix the issue I'm describing. It's however
once every minute, so perhaps another strategy can be considered as a new node joining the cluster possible won't have the correct topology for ~1 minute.

**To Reproduce**
1. Start two nodes, be sure to be running a user function on 8080:
```bash
# Will discover user function on 8080
NODE_COOKIE=secret PROXY_PORT=5000 PROXY_HTTP_PORT=5001 iex --name massa-001@127.0.0.1 -S mix

# Will have no entities
USER_FUNCTION_PORT=4000 NODE_COOKIE=secret iex --name massa-002@127.0.0.1 --cookie secret -S mix
```
2. Call `GenServer.call(MassaProxy.Entity.EntityRegistry, {:get, "cloudstate.action.ActionProtocol"})` to see that it's empty

**Expected behavior**
A node joining a cluster should receive information about the entities that is registered stred on that *node*.
I.e when a `EntityRegistry` receives a join message from it should respond to the node with the entities.

### PR DESCRIPTION
**Pull request by drowzy**
Introduces a slight change to the protocol between entity registries. Instead of relying on discovery to kick in to send information all nodes, this change allows for nodes to send *their* current state to the joining node when it receives a join message. So the issues observed in #91 where a joining node does not receive any entity information up to 60 seconds after it successfully joined the cluster is fixed. 

This will allow for instance to send deltas of changes picked up in discovery, as the full state would have been transmitted on join.

### CODE REVIEW

**Comment by sleipnir** [comment]
Thank you @drowzy

File: apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex [hunk 1]
```diff
@@ -49,7 +60,7 @@ defmodule MassaProxy.Entity.EntityRegistry do
     PubSub.broadcast(
       :entity_channel,
       @topic,
-      {:join, %{node => new_entities}}
+      {:new_entities, %{node => new_entities}}
```
Comment (sleipnir) [inline apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex:63]: instead new_entities why not incoming_entities 
it won't always be a New entity, sometimes it's just the same entity but coming from another proxy instance

**Review by sleipnir — CHANGES_REQUESTED** [review]

File: apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex (hunk 1 above)
Comment (drowzy) [reply apps/massa_proxy/lib/massa_proxy/cluster/entity/entity_registry.ex:63]: Agree, good suggestion!

**Review by sleipnir — APPROVED** [review]
